apiVersion: v1
kind: Namespace
metadata:
  name: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: myapp
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: node:18-alpine
        command: ["node"]
        args: ["-e", "const http = require('http'); const server = http.createServer((req, res) => { res.writeHead(200); res.end('Hello from Pod: ' + require('os').hostname() + '\\n'); }); server.listen(3000, '0.0.0.0');"]
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: myapp
spec:
  selector:
    app: nodejs
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort